---
services:
  umami:
    image: ghcr.io/umami-software/umami:latest
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      DATABASE_URL: ${CONNECTION_STRING}
      APP_SECRET: ${APP_SECRET}
    init: true
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:${APP_PORT}/api/heartbeat"]
      interval: 5s
      timeout: 5s
      retries: 5
