---
services:
  umami:
    image: ghcr.io/umami-software/umami:latest
    ports:
      - "0.0.0.0:${APP_PORT}:${APP_PORT}"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      APP_SECRET: ${APP_SECRET}
      APP_PORT: ${APP_PORT}
    init: true
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:${APP_PORT}/api/heartbeat"]
      interval: 5s
      timeout: 5s
      retries: 5
